data_source my_ds:
  type: snowflake
  connection:
    account: ${SNOWFLAKE_ACCOUNT}
    user: ${SNOWFLAKE_USER}
    password: ${SNOWFLAKE_PASSWORD}
    database: ${SNOWFLAKE_DATABASE}
    warehouse: ${SNOWFLAKE_WAREHOUSE}
    role: ${SNOWFLAKE_ROLE}
  schema: ${SNOWFLAKE_SCHEMA_RAW}

  checks:
    - stales not allowed:
        warn: when > 1h
        fail: when > 24h