name: 'fitbit_air'
version: '1.0.0'
config-version: 2

profile: 'fitbit_air'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  fitbit_air:
    silver:
      +materialized: view
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
